services:
  db:
    image: postgres:15.7
    environment:
      POSTGRES_DB: hh_db
      POSTGRES_USER: hh_user
      POSTGRES_PASSWORD: hh_password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5400:5432

  backend:
    build:
      context: ./backend
    container_name: hh_backend
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: hh_frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  db_data:

#благодаря этому файлу вся система поднимается вместе, с помощью Docker-контейнеров